
-- ===========================================================
-- Phase IV: Create Pluggable Database
-- HEMMS Project
-- Student: Habanabashaka Philimin
-- ===========================================================

CREATE PLUGGABLE DATABASE A_27487_PHILIMIN_HEMMS_DB
    ADMIN USER hemms_admin IDENTIFIED BY philimin
    ROLES = (DBA)
    DEFAULT TABLESPACE USERS
    DATAFILE 'C:\APP\ORADATA\XE\A_27487_PHILIMIN_HEMMS_DB\users01.dbf'
        SIZE 250M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED
    FILE_NAME_CONVERT = (
        'C:\APP\ORADATA\XE\PDBSEED\',
        'C:\APP\ORADATA\XE\A_27487_PHILIMIN_HEMMS_DB\'
    )
    STORAGE (MAXSIZE UNLIMITED);

ALTER PLUGGABLE DATABASE A_27487_PHILIMIN_HEMMS_DB OPEN;
ALTER PLUGGABLE DATABASE A_27487_PHILIMIN_HEMMS_DB SAVE STATE;

ALTER SESSION SET CONTAINER = A_27487_PHILIMIN_HEMMS_DB;

